---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include blueprints.vault_integrations.ldap_auth with caller-supplied variables
      ansible.builtin.include_role:
        name: blueprints.vault_integrations.ldap_auth
      vars:
        vault_integration_ldap_endpoint: "https://example.invalid"
